const employees = [
    { "ID": 1, "Name": "John Smith" },
    { "ID": 2, "Name": "Sarah Johnson" },
    { "ID": 3, "Name": "Michael Brown" },
    { "ID": 4, "Name": "Jessica Lee" },
    { "ID": 5, "Name": "David Wilson" },
    { "ID": 6, "Name": "Emily Davis" },
    { "ID": 7, "Name": "Andrew Clark" },
    { "ID": 8, "Name": "Olivia Wright" },
    { "ID": 9, "Name": "Ethan Turner" },
    { "ID": 10, "Name": "Emma Hall" },
    { "ID": 11, "Name": "William White" },
    { "ID": 12, "Name": "Sophia Anderson" },
    { "ID": 13, "Name": "James Martinez" },
    { "ID": 14, "Name": "Ava Thompson" },
    { "ID": 15, "Name": "Benjamin Harris" },
    { "ID": 16, "Name": "Mia Walker" },
    { "ID": 17, "Name": "Alexander Lewis" },
    { "ID": 18, "Name": "Harper Baker" },
    { "ID": 19, "Name": "Daniel Green" },
    { "ID": 20, "Name": "Amelia Taylor" },
    { "ID": 21, "Name": "Samuel Young" },
    { "ID": 22, "Name": "Charlotte Hill" },
    { "ID": 23, "Name": "Joseph Cooper" },
    { "ID": 24, "Name": "Grace Garcia" },
    { "ID": 25, "Name": "Jackson Allen" },
    { "ID": 26, "Name": "Madison Cook" },
    { "ID": 27, "Name": "Henry Ross" },
    { "ID": 28, "Name": "Lily Nelson" },
    { "ID": 29, "Name": "Isaac Murphy" },
    { "ID": 30, "Name": "Harper Collins" }
    
  ];
  
  export default employees;